# Generated by Django 5.2.10 on 2026-01-19 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='adress',
            new_name='address',
        ),
    ]
